### ISSUE TITLE
Milestone 1: Metadata Panel and Rulers

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#114]
## Metadata Panel

As a user, I would like to see some additional information about the image I have loaded

- [x] #103 
- [x] #104 
- [x] #102 
- [x] #38 
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/94

## Rulers

As a user, I would like to have a sense of the physical scale of the structures I am viewing.

- [x] https://github.com/allen-cell-animated/volume-viewer/issues/79
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/66

## Bug Fixes

- [x] #115 
- [x] #122
