### ISSUE TITLE
Milestone 3: Time Series optimizations

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#155]
## Time Series Zarr Optimization

- [x] https://github.com/allen-cell-animated/volume-viewer/issues/110
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/112
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/111
- [x] #163
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/113
- [ ] #165 
- [ ] bonus: https://github.com/allen-cell-animated/volume-viewer/issues/115
- [ ] bonus: https://github.com/allen-cell-animated/volume-viewer/issues/102
- [ ] bonus: https://github.com/allen-cell-animated/volume-viewer/issues/121
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/123
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/126
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/134
- [ ] https://github.com/allen-cell-animated/volume-viewer/issues/133
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/132
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/131
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/152
- [ ] https://github.com/allen-cell-animated/volume-viewer/issues/155
- [x] https://github.com/allen-cell-animated/volume-viewer/issues/157

note that XY mode is "special" vs YZ and XZ modes which require transverse projections across many slices.

**Comment by frasercl** [comment]
While we're rearchitecting large sections of volume-viewer, it may be good to work in allen-cell-animated/volume-viewer#90

**Comment by toloudis** [comment]
Notes on potential task breakdown

- implement a unit testable cache module for typedarrays
- implement a unit testable request queue (unit test via mocking a server that returns arrays)
- volumeloader api changes to fetch slices (rename to volumedatasource?)
- new XY mode shader, invoked via RayMarchVolumeRendering perhaps? 
-- first implementation which draws from a subregion of the tiled atlas
-- final implementation draws a texture which contains the whole slice so it's not a subregion
- business logic when to issue the requests, how does the cache give data back to the viewer, turn it into textures etc.

**Comment by ShrimpCryptid** [comment]
### Design Questions
**1. What happens and who gets notified when we switch modes?**
 - Integration of changes across the viewer (view3D -> VolumeDrawable + Three.js Canvas -> ray march renderer + RequestQueue + cache)

**2. How do we fetch single Z-slices for multi-channel data?** 
 - Optimize for chunks containing multiple slices (no redundant requests?)
 - Add something to zarr loader to fetch slices

**3. How do we prepare multi-channel data for rendering?
4. When does pre-fetching need to happen?**

**5. How do we cancel a fetch operation (or operations)?**
 - Implementing a RequestQueue
 - Unit testing (mocking, test server, let requests complete at different time intervals)
 - Observer pattern -> observe completion/rejection of request
 - Check if requests overlap with existing requests, drop other requests in flight

**6. Who's responsible for determining when pre-fetching happens?**
 - ❌ First time user loads any volume data
 - First time user clicks on XY mode
 - Anytime user changes time while in XY mode
 - ^ 2 event handlers, each issue request to RequestQueue 

**7. What do we do when a fetch is completed (data arrives at the client?) -> RequestQueue**
**8. What happens when a user is in XY mode and changes time?**
   - Cancel all current requests
   - Request new frame data

**Comment by toloudis** [comment]
Calling this done for the sake of the next milestone!!!
At this time we have stable time series loading and playback of ome-zarr datasets characteristic of AICS (~1000x1000x100, T=~500, with at least 4 pre-generated downsampled resolutions.)
